//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 05:15:41 PM CEST 
//


package uma.caosd.AspectualKnowledge;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdaptationPlan complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdaptationPlan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="instance" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}Instance"/>
 *         &lt;element name="ADD" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}ADD"/>
 *         &lt;element name="REMOVE" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}REMOVE"/>
 *         &lt;element name="CONFIGURE" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}CONFIGURE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdaptationPlan", propOrder = {
    "instance",
    "add",
    "remove",
    "configure"
})
public class AdaptationPlan {

    @XmlElement(required = true)
    protected Instance instance;
    @XmlElement(name = "ADD", required = true)
    protected ADD add;
    @XmlElement(name = "REMOVE", required = true)
    protected REMOVE remove;
    @XmlElement(name = "CONFIGURE", required = true)
    protected CONFIGURE configure;

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link Instance }
     *     
     */
    public Instance getInstance() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Instance }
     *     
     */
    public void setInstance(Instance value) {
        this.instance = value;
    }

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link ADD }
     *     
     */
    public ADD getADD() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADD }
     *     
     */
    public void setADD(ADD value) {
        this.add = value;
    }

    /**
     * Gets the value of the remove property.
     * 
     * @return
     *     possible object is
     *     {@link REMOVE }
     *     
     */
    public REMOVE getREMOVE() {
        return remove;
    }

    /**
     * Sets the value of the remove property.
     * 
     * @param value
     *     allowed object is
     *     {@link REMOVE }
     *     
     */
    public void setREMOVE(REMOVE value) {
        this.remove = value;
    }

    /**
     * Gets the value of the configure property.
     * 
     * @return
     *     possible object is
     *     {@link CONFIGURE }
     *     
     */
    public CONFIGURE getCONFIGURE() {
        return configure;
    }

    /**
     * Sets the value of the configure property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONFIGURE }
     *     
     */
    public void setCONFIGURE(CONFIGURE value) {
        this.configure = value;
    }

}
