//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 05:15:41 PM CEST 
//


package uma.caosd.AspectualKnowledge;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Advisor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Advisor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="configuration" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}AdvisorConfiguration" minOccurs="0"/>
 *         &lt;element name="pointcut" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}Pointcut" minOccurs="0"/>
 *         &lt;element name="advice" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}Advice" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="advice-ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pointcut-ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}AOPType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Advisor", propOrder = {
    "configuration",
    "pointcut",
    "advice"
})
public class Advisor {

    protected AdvisorConfiguration configuration;
    protected Pointcut pointcut;
    protected Advice advice;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "advice-ref")
    protected String adviceRef;
    @XmlAttribute(name = "pointcut-ref")
    protected String pointcutRef;
    @XmlAttribute(name = "type")
    protected AOPType type;

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link AdvisorConfiguration }
     *     
     */
    public AdvisorConfiguration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdvisorConfiguration }
     *     
     */
    public void setConfiguration(AdvisorConfiguration value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the pointcut property.
     * 
     * @return
     *     possible object is
     *     {@link Pointcut }
     *     
     */
    public Pointcut getPointcut() {
        return pointcut;
    }

    /**
     * Sets the value of the pointcut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pointcut }
     *     
     */
    public void setPointcut(Pointcut value) {
        this.pointcut = value;
    }

    /**
     * Gets the value of the advice property.
     * 
     * @return
     *     possible object is
     *     {@link Advice }
     *     
     */
    public Advice getAdvice() {
        return advice;
    }

    /**
     * Sets the value of the advice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Advice }
     *     
     */
    public void setAdvice(Advice value) {
        this.advice = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the adviceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdviceRef() {
        return adviceRef;
    }

    /**
     * Sets the value of the adviceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdviceRef(String value) {
        this.adviceRef = value;
    }

    /**
     * Gets the value of the pointcutRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointcutRef() {
        return pointcutRef;
    }

    /**
     * Sets the value of the pointcutRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointcutRef(String value) {
        this.pointcutRef = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AOPType }
     *     
     */
    public AOPType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AOPType }
     *     
     */
    public void setType(AOPType value) {
        this.type = value;
    }

}
