//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 05:15:41 PM CEST 
//


package uma.caosd.AspectualKnowledge;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AspectualKnowledge complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AspectualKnowledge">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pointcuts" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}Pointcuts"/>
 *         &lt;element name="advices" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}Advices"/>
 *         &lt;element name="advisors" type="{http://inter-trust.eu/schema/AspectualKnowledge/ak}Advisors"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AspectualKnowledge", propOrder = {
    "pointcuts",
    "advices",
    "advisors"
})
public class AspectualKnowledge {

    @XmlElement(required = true)
    protected Pointcuts pointcuts;
    @XmlElement(required = true)
    protected Advices advices;
    @XmlElement(required = true)
    protected Advisors advisors;

    /**
     * Gets the value of the pointcuts property.
     * 
     * @return
     *     possible object is
     *     {@link Pointcuts }
     *     
     */
    public Pointcuts getPointcuts() {
        return pointcuts;
    }

    /**
     * Sets the value of the pointcuts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pointcuts }
     *     
     */
    public void setPointcuts(Pointcuts value) {
        this.pointcuts = value;
    }

    /**
     * Gets the value of the advices property.
     * 
     * @return
     *     possible object is
     *     {@link Advices }
     *     
     */
    public Advices getAdvices() {
        return advices;
    }

    /**
     * Sets the value of the advices property.
     * 
     * @param value
     *     allowed object is
     *     {@link Advices }
     *     
     */
    public void setAdvices(Advices value) {
        this.advices = value;
    }

    /**
     * Gets the value of the advisors property.
     * 
     * @return
     *     possible object is
     *     {@link Advisors }
     *     
     */
    public Advisors getAdvisors() {
        return advisors;
    }

    /**
     * Sets the value of the advisors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Advisors }
     *     
     */
    public void setAdvisors(Advisors value) {
        this.advisors = value;
    }

}
