//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 05:15:41 PM CEST 
//


package uma.caosd.AspectualKnowledge;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uma.caosd.AspectualKnowledge package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Configuration_QNAME = new QName("http://inter-trust.eu/schema/AspectualKnowledge/ak", "configuration");
    private final static QName _AdaptationPlan_QNAME = new QName("http://inter-trust.eu/schema/AspectualKnowledge/ak", "adaptationPlan");
    private final static QName _AspectualKnowledge_QNAME = new QName("http://inter-trust.eu/schema/AspectualKnowledge/ak", "aspectualKnowledge");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uma.caosd.AspectualKnowledge
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AspectualKnowledge }
     * 
     */
    public AspectualKnowledge createAspectualKnowledge() {
        return new AspectualKnowledge();
    }

    /**
     * Create an instance of {@link AdaptationPlan }
     * 
     */
    public AdaptationPlan createAdaptationPlan() {
        return new AdaptationPlan();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link Advices }
     * 
     */
    public Advices createAdvices() {
        return new Advices();
    }

    /**
     * Create an instance of {@link AdvisorConfiguration }
     * 
     */
    public AdvisorConfiguration createAdvisorConfiguration() {
        return new AdvisorConfiguration();
    }

    /**
     * Create an instance of {@link CONFIGURE }
     * 
     */
    public CONFIGURE createCONFIGURE() {
        return new CONFIGURE();
    }

    /**
     * Create an instance of {@link Advisors }
     * 
     */
    public Advisors createAdvisors() {
        return new Advisors();
    }

    /**
     * Create an instance of {@link Advice }
     * 
     */
    public Advice createAdvice() {
        return new Advice();
    }

    /**
     * Create an instance of {@link Functionalities }
     * 
     */
    public Functionalities createFunctionalities() {
        return new Functionalities();
    }

    /**
     * Create an instance of {@link Pointcut }
     * 
     */
    public Pointcut createPointcut() {
        return new Pointcut();
    }

    /**
     * Create an instance of {@link Pointcuts }
     * 
     */
    public Pointcuts createPointcuts() {
        return new Pointcuts();
    }

    /**
     * Create an instance of {@link REMOVE }
     * 
     */
    public REMOVE createREMOVE() {
        return new REMOVE();
    }

    /**
     * Create an instance of {@link AdviceCategory }
     * 
     */
    public AdviceCategory createAdviceCategory() {
        return new AdviceCategory();
    }

    /**
     * Create an instance of {@link ConfigurationParameters }
     * 
     */
    public ConfigurationParameters createConfigurationParameters() {
        return new ConfigurationParameters();
    }

    /**
     * Create an instance of {@link Advisor }
     * 
     */
    public Advisor createAdvisor() {
        return new Advisor();
    }

    /**
     * Create an instance of {@link Functionality }
     * 
     */
    public Functionality createFunctionality() {
        return new Functionality();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link AdvisorCategory }
     * 
     */
    public AdvisorCategory createAdvisorCategory() {
        return new AdvisorCategory();
    }

    /**
     * Create an instance of {@link ADD }
     * 
     */
    public ADD createADD() {
        return new ADD();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Configuration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://inter-trust.eu/schema/AspectualKnowledge/ak", name = "configuration")
    public JAXBElement<Configuration> createConfiguration(Configuration value) {
        return new JAXBElement<Configuration>(_Configuration_QNAME, Configuration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdaptationPlan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://inter-trust.eu/schema/AspectualKnowledge/ak", name = "adaptationPlan")
    public JAXBElement<AdaptationPlan> createAdaptationPlan(AdaptationPlan value) {
        return new JAXBElement<AdaptationPlan>(_AdaptationPlan_QNAME, AdaptationPlan.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AspectualKnowledge }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://inter-trust.eu/schema/AspectualKnowledge/ak", name = "aspectualKnowledge")
    public JAXBElement<AspectualKnowledge> createAspectualKnowledge(AspectualKnowledge value) {
        return new JAXBElement<AspectualKnowledge>(_AspectualKnowledge_QNAME, AspectualKnowledge.class, null, value);
    }

}
