//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 10:37:44 AM CEST 
//


package uma.caosd.SecurityDeploymentSpecification;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for undeploy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="undeploy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="undeploySecurityFeature" type="{http://inter-trust.eu/schema/interpreter/sds}undeploySecurityFeature" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "undeploy", propOrder = {
    "undeploySecurityFeature"
})
public class Undeploy {

    @XmlElement(required = true)
    protected List<UndeploySecurityFeature> undeploySecurityFeature;

    /**
     * Gets the value of the undeploySecurityFeature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the undeploySecurityFeature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUndeploySecurityFeature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UndeploySecurityFeature }
     * 
     * 
     */
    public List<UndeploySecurityFeature> getUndeploySecurityFeature() {
        if (undeploySecurityFeature == null) {
            undeploySecurityFeature = new ArrayList<UndeploySecurityFeature>();
        }
        return this.undeploySecurityFeature;
    }

}
