package intertrust.modules.ag;

import intertrust.modules.aw.AspectWeaver;

/**
 * Concrete Aspect Generation module.
 * Basic functionality of the aspect generation module for a specific dependent AOP framework.
 * 
 * This module completes the generic security adaptation plan generated by the 
 * generic aspect generation sub-module with information specific of the AOP
 * framework used for a particular instantiation of the INTER-TRUST framework. 
 * Its input is the generic security adaptation plan (GenericAspectsAdaptationRequestInt interface),
 * and its output is a concrete security adaptation plan (Concrete AspectsAdaptationRequestInt interface). 
 * //It is composed by two internal components: Concrete Security Adaptation Plan Generation and 
 * Concrete Aspect Generation.
 * 
 * @author UMA
 * @date   19/09/2013
 *
 */
public abstract class ConcreteAspectGeneration implements GenericAspectsAdaptationRequestInt, GenerationOfNewAspectRequestInt {

	private AspectWeaver aw;
	
	/**
	 * Creates a new instance of the concrete aspect generation,
	 * with the indicated aspect weaver.
	 * 
	 * @param concreteAW	Aspect weaver.
	 */
	public ConcreteAspectGeneration(AspectWeaver concreteAW) {
		aw = concreteAW;
		aw.setAspectGeneration(this);
	}

	/**
	 * 
	 * @return Aspect weaver module.
	 */
	public AspectWeaver getAspectWeaver() {
		return aw;
	}

	/**
	 * 
	 * @param aw	New Aspect weaver module.
	 */
	public void setAspectWeaver(AspectWeaver aw) {
		this.aw = aw;
	}
	
}
