package intertrust.modules.aw;

import intertrust.modules.ag.ConcreteAspectGeneration;

/**
 * Concrete Aspect Weaver module.
 * Basic functionality of the aspect weaver module for a specific dependent AOP framework.
 * 
 * The aspect weaver module will allow adding and deleting aspects. 
 * This module executes the adaptation plan generated by the aspect generation module
 * (the list of aspects to be added/deleted). 
 * Thus the information generated by the Aspect Generation Module is the input to the
 * Execute the Security Adaptation Plan component which will be specifically 
 * implemented for each AOP framework that may be used in the project. 
 * This component is a wrapper that will translate the list of aspects received 
 * as input (which is specified independently of a particular AOP framework)
 * to the particular syntax of the particular AOP weaver being used. 
 * This means that different instantiations of the INTER-TRUST framework 
 * for using different AOP weavers will provide different implementations of this component. 
 * The output of this component is a direct interaction with the selected AOP weaver
 * in order to interact with it and to weave/unweave the corresponding aspects into the applications.
 * 
 * @author UMA
 * @date   19/09/2013
 *
 */
public abstract class AspectWeaver implements AspectsAdaptationRequestInt {
	
	protected ConcreteAspectGeneration ag;
	
	public void setAspectGeneration(ConcreteAspectGeneration concreteAG) {
		ag = concreteAG;
	}
	
}
