//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.12 at 12:46:37 PM CEST 
//


package uma.caosd.errors;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Module.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Module">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AspectGeneration"/>
 *     &lt;enumeration value="AspectWeaver"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Module")
@XmlEnum
public enum Module {

    @XmlEnumValue("AspectGeneration")
    ASPECT_GENERATION("AspectGeneration"),
    @XmlEnumValue("AspectWeaver")
    ASPECT_WEAVER("AspectWeaver");
    private final String value;

    Module(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Module fromValue(String v) {
        for (Module c: Module.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
