//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.12 at 12:46:37 PM CEST 
//


package uma.caosd.errors;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uma.caosd.errors package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeploymentStatus_QNAME = new QName("http://www.example.org/Errors-schema", "DeploymentStatus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uma.caosd.errors
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeploymentStatus }
     * 
     */
    public DeploymentStatus createDeploymentStatus() {
        return new DeploymentStatus();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeploymentStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Errors-schema", name = "DeploymentStatus")
    public JAXBElement<DeploymentStatus> createDeploymentStatus(DeploymentStatus value) {
        return new JAXBElement<DeploymentStatus>(_DeploymentStatus_QNAME, DeploymentStatus.class, null, value);
    }

}
