//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.12 at 12:46:37 PM CEST 
//


package uma.caosd.errors;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SDS"/>
 *     &lt;enumeration value="SAK"/>
 *     &lt;enumeration value="internal"/>
 *     &lt;enumeration value="Mapping"/>
 *     &lt;enumeration value="AspectsSelection"/>
 *     &lt;enumeration value="AspectJWeaver"/>
 *     &lt;enumeration value="SpringAOPWeaver"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Type")
@XmlEnum
public enum Type {

    SDS("SDS"),
    SAK("SAK"),
    @XmlEnumValue("internal")
    INTERNAL("internal"),
    @XmlEnumValue("Mapping")
    MAPPING("Mapping"),
    @XmlEnumValue("AspectsSelection")
    ASPECTS_SELECTION("AspectsSelection"),
    @XmlEnumValue("AspectJWeaver")
    ASPECT_J_WEAVER("AspectJWeaver"),
    @XmlEnumValue("SpringAOPWeaver")
    SPRING_AOP_WEAVER("SpringAOPWeaver");
    private final String value;

    Type(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Type fromValue(String v) {
        for (Type c: Type.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
